---
namespace: ginigangadharan
name: network_utilities
version: 0.0.6
readme: README.md
authors:
  - Gineesh Madapparambath <net.gini@gmail.com>
description: Ansible Network Utlities
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - demos
  - ansible
  - network

dependencies:
  "cisco.asa": ">=3.0.0"
  "cisco.nxos": ">=3.0.0"
repository: https://github.com/ginigangadharan/ansible-collection-network-utilities
documentation: https://github.com/ginigangadharan/ansible-collection-network-utilities
homepage: https://github.com/ginigangadharan/ansible-collection-network-utilities
issues: https://github.com/ginigangadharan/ansible-collection-network-utilities/issues

#build_ignore:
#- .gitignore
#- changelogs/.plugin-cache.yaml
